apiVersion: v1
kind: Pod
metadata:
  name: kafkacat
spec:
  containers:
  - name: kafkacat
    image: confluentinc/cp-kcat:7.5.1
    command: 
      - "sh"
      - "-c"
      - |
        # Create kcat config file
        cat > /tmp/kcat.conf << EOF
        bootstrap.servers=streaming-kafka-cluster-kafka-bootstrap:9092
        security.protocol=SASL_PLAINTEXT
        sasl.mechanism=SCRAM-SHA-256
        sasl.username=kafka-user
        sasl.password=$(cat /etc/kafka-user/password)
        EOF
        
        echo "=== Kafka User Configuration Ready ==="
        echo "Config file: /tmp/kcat.conf"
        echo "Username: kafka-user"
        echo "Bootstrap: streaming-kafka-cluster-kafka-bootstrap:9092"
        echo "========================================="
        echo ""
        echo "Usage examples:"
        echo "  List topics: kcat -F /tmp/kcat.conf -L"
        echo "  Produce: echo 'test' | kcat -F /tmp/kcat.conf -t trading-prices -P"
        echo "  Consume: kcat -F /tmp/kcat.conf -t trading-prices -C"
        echo ""
        exec tail -f /dev/null
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "250m"
    volumeMounts:
    - name: kafka-user-secret
      mountPath: "/etc/kafka-user"
      readOnly: true
    - name: cluster-ca-cert
      mountPath: "/etc/kafka-ca"
      readOnly: true
    env:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: "streaming-kafka-cluster-kafka-bootstrap:9092"
    - name: KAFKA_USERNAME
      value: "kafka-user"
    - name: KAFKA_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kafka-user
          key: password
  volumes:
  - name: kafka-user-secret
    secret:
      secretName: kafka-user
  - name: cluster-ca-cert
    secret:
      secretName: streaming-kafka-cluster-cluster-ca-cert