apiVersion: v1
kind: Pod
metadata:
  name: kafka-cli
  namespace: kafka
spec:
  containers:
    - name: kafka-cli
      image: bitnami/kafka
      command:
        - /bin/sh
        - -c
        - |
          keytool -import -trustcacerts -alias ca -file /etc/kafka-ca/ca.crt -keystore /tmp/truststore.jks -storepass password -noprompt
          cat > /tmp/client.properties <<EOF
          security.protocol=SASL_SSL
          sasl.mechanism=SCRAM-SHA-512
          sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="kafka-user" password="$(cat /etc/kafka-user/password)";
          ssl.truststore.location=/tmp/truststore.jks
          ssl.truststore.password=password
          EOF
          sleep infinity
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "500m"
      volumeMounts:
        - name: kafka-user-secret
          mountPath: /etc/kafka-user
          readOnly: true
        - name: cluster-ca-cert
          mountPath: /etc/kafka-ca
          readOnly: true
  volumes:
    - name: kafka-user-secret
      secret:
        secretName: kafka-user
    - name: cluster-ca-cert
      secret:
        secretName: streaming-kafka-cluster-cluster-ca-cert