apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: combined-nodes
  labels:
    strimzi.io/cluster: streaming-kafka-cluster
spec:
  replicas: 3
  roles:
    - controller
    - broker
  template:
    pod:
      tolerations:
      - key: "app.stateful/component"
        operator: "Equal"
        value: "kafka-broker"
        effect: NoSchedule
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: "app.stateful/component"
                operator: In
                values:
                - "kafka-broker"
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: kafka
            strimzi.io/cluster: streaming-kafka-cluster
            strimzi.io/component-type: kafka
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: kafka
            strimzi.io/cluster: streaming-kafka-cluster
            strimzi.io/component-type: kafka
  resources:
    requests:
      memory: 2Gi
      cpu: "500m"
    limits:
      memory: 2Gi
      cpu: "1"
  jvmOptions:
    -Xms: 1536m
    -Xmx: 1536m
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 20Gi
        class: standard-rwo
        deleteClaim: false

---

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: streaming-kafka-cluster
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 4.0.0
    metadataVersion: 4.0-IV3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
    config:
      offsets.topic.replication.factor: 3
      default.replication.factor: 3
      min.insync.replicas: 2
  entityOperator:
    topicOperator:
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 200m
          memory: 512Mi
    userOperator:
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 500m
          memory: 1Gi
